project_id = "tcyulkuyfptlisfyefnn"

[global.env]
SUPABASE_URL = "env"
SUPABASE_SERVICE_ROLE_KEY = "env"
SUPABASE_DB_URL = "env"

[[functions]]
name = "backup-storage"
verify_jwt = true

[[functions]]
name = "check-move-distance"
verify_jwt = true

[[functions]]
name = "create-stripe-customer"
verify_jwt = true

[[functions]]
name = "create-subscription"
verify_jwt = true

[[functions]]
name = "generate-invoice"
verify_jwt = true

[[functions]]
name = "geocode-address"
verify_jwt = true

[[functions]]
name = "get-client-ip"
verify_jwt = false

[[functions]]
name = "handle_new_user"
verify_jwt = false

[[functions]]
name = "monitor-backups"
verify_jwt = true

[[functions]]
name = "notify-companies"
verify_jwt = true

[[functions]]
name = "perform-database-backup"
verify_jwt = true

[[functions]]
name = "perform-incremental-backup"
verify_jwt = true

[[functions]]
name = "process-matches"
verify_jwt = true

[[functions]]
name = "process-payment"
verify_jwt = true

[[functions]]
name = "register-company"
verify_jwt = true

[[functions]]
name = "report-usage"
verify_jwt = true

[[functions]]
name = "send-confirmation-email"
verify_jwt = true

[[functions]]
name = "send-verification-email"
verify_jwt = true

[[functions]]
name = "send-welcome-email"
verify_jwt = true

[[functions]]
name = "stripe-webhook"
verify_jwt = false

[[functions]]
name = "verify-company"
verify_jwt = true

[[functions]]
name = "validate-move-request"
verify_jwt = true