
project_id = "tcyulkuyfptlisfyefnn"

[global.env]
SUPABASE_URL = "env"
SUPABASE_SERVICE_ROLE_KEY = "env"
SUPABASE_DB_URL = "env"

[[functions]]
name = "register-company"
verify_jwt = false

[[functions]]
name = "notify-companies"
verify_jwt = false

[[functions]]
name = "submit-move-request"
verify_jwt = false

[[functions]]
name = "calculate-move-estimate"
verify_jwt = false
