// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcyulkuyfptlisfyefnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjeXVsa3V5ZnB0bGlzZnllZm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MTQ0MzYsImV4cCI6MjA1MDQ5MDQzNn0.BCfN7FMzY2hDp26NGOWqrV197j2EztDEoplL0CF5_gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);